version: '3.8'

services:

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    container_name: lc_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MINIO_ENDPOINT: minio:9000
      STORAGE_BUCKET: uploads
      REDIS_URL: redis://redis:6379/1
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      CELERY_BROKER: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672//
      CELERY_BACKEND: redis://redis:6379/0

      # ML service URLs
      ML_CT_URL: http://ml_ct:8101/predict
      ML_IMAGE_URL: http://ml_image:8110/predict
      ML_AUDIO_URL: http://ml_audio:8102/predict
      ML_META_URL: http://ml_meta:8103/predict
      ML_FUSION_URL: http://ml_fusion:8104/predict
    depends_on:
      - redis
      - rabbitmq
      - postgres
      - minio
      - ml_ct
      - ml_audio
      - ml_meta
      - ml_fusion
      - ml_image
    volumes:
      - ./services/api/app:/app

  worker:
    build:
      context: ./services/worker
      dockerfile: Dockerfile
    container_name: lc_worker
    env_file:
      - .env
    environment:
      MINIO_ENDPOINT: minio:9000
      STORAGE_BUCKET: uploads
      REDIS_URL: redis://redis:6379/1
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      CELERY_BROKER: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672//
      CELERY_BACKEND: redis://redis:6379/0

      # ML URLs
      ML_CT_URL: http://ml_ct:8101/predict
      ML_IMAGE_URL: http://ml_image:8110/predict
      ML_AUDIO_URL: http://ml_audio:8102/predict
      ML_META_URL: http://ml_meta:8103/predict
      ML_FUSION_URL: http://ml_fusion:8104/predict
    depends_on:
      - redis
      - rabbitmq
      - minio
      - ml_ct
      - ml_audio
      - ml_meta
      - ml_fusion
      - ml_image
    volumes:
      - ./services/worker:/app

  ml_ct:
    build:
      context: ./services/ml_service_ct
      dockerfile: Dockerfile
    container_name: lc_ml_ct
    env_file:
      - .env
    environment:
      PORT: 8101
    ports:
      - "8101:8101"
    volumes:
      - ./services/ml_service_ct/service:/app/service

  ml_audio:
    build:
      context: ./services/ml_service_audio
      dockerfile: Dockerfile
    container_name: lc_ml_audio
    environment:
      PORT: 8102
    ports:
      - "8102:8102"
    volumes:
      - ./services/ml_service_audio/service:/app/service

  ml_meta:
    build:
      context: ./services/ml_service_metadata
      dockerfile: Dockerfile
    container_name: lc_ml_meta
    environment:
      PORT: 8103
    ports:
      - "8103:8103"
    volumes:
      - ./services/ml_service_metadata/service:/app/service

  ml_fusion:
    build:
      context: ./services/ml_service_fusion
      dockerfile: Dockerfile
    container_name: lc_ml_fusion
    environment:
      PORT: 8104
    ports:
      - "8104:8104"
    volumes:
      - ./services/ml_service_fusion/service:/app/service

  rabbitmq:
    image: rabbitmq:3-management
    container_name: lc_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  redis:
    image: redis:7
    container_name: lc_redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    container_name: lc_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:15
    container_name: lc_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ml_image:
    build:
      context: ./services/ml_service_image
      dockerfile: Dockerfile
    container_name: lc_ml_image
    env_file:
      - .env
    environment:
      PORT: 8110
      MINIO_ENDPOINT: minio:9000
      STORAGE_BUCKET: uploads
      IMAGE_MODEL_PATH: /app/models/image_classifier.pt
    ports:
      - "8110:8110"
    volumes:
      - ./services/ml_service_image/service:/app/service



volumes:
  minio_data:
  pgdata:
